import logging

import ollama
from langchain_core.messages import BaseMessage
from langchain_ollama import ChatOllama

from .base import BaseLLM

logger = logging.getLogger(__name__)


class OllamaModel(BaseLLM):
    """
    Ollama-based LLM implementation.
    """

    def __init__(
        self,
        model_name: str = "llama2",
        host: str = "localhost",
        port: int = 11434,
        ssl: bool = False,
        **kwargs,
    ):
        """
        Initialize the Ollama model and verify its availability.

        Parameters
        ----------
        model_name : str, default "llama2"
            The name of the LLM to use.
        host : str, default "localhost"
            The hostname where the Ollama server is running.
        port : int, default 11434
            The API port for the Ollama service.
        ssl : bool, default False
            Whether to use a secure HTTPS connection.
        **kwargs : dict
            Additional arguments passed to the ChatOllama constructor 
            (e.g., temperature, num_predict).

        Raises
        ------
        ollama.ResponseError
            If there is a critical failure communicating with the Ollama server.
        """
        protocol = "https" if ssl else "http"
        base_url = f"{protocol}://{host}:{port}"

        # Verify model availability on the Ollama server
        client = ollama.Client(host=base_url)
        try:
            client.show(model_name)
        except ollama.ResponseError as e:
            logger.warning(f"Model '{model_name}' not found on Ollama server.")
            logger.info(f"Downloading (pulling) model '{model_name}'... This may take a while.")
            if e.status_code == 404:
                client.pull(model_name)
                logger.info(f"Model '{model_name}' pulled successfully.")
            else:
                logger.error(f"Failed to communicate with Ollama: {e}")
                raise e

        # LangChain-compatible chat model
        self._llm = ChatOllama(model=model_name, base_url=base_url, **kwargs)

    def generate(self, messages: list[BaseMessage]) -> str:
        """
        Generate a text response from a list of structured messages.

        Parameters
        ----------
        messages : list[BaseMessage]
            A sequence of Human, System, or AI messages.

        Returns
        -------
        str
            The text content generated by the model.
        """
        response = self._llm.invoke(messages)
        return response.content

    @property
    def runnable(self):
        """
        Expose the underlying LangChain runnable.

        Returns
        -------
        ChatOllama
            The ChatOllama instance for use in LCEL chains.
        """
        return self._llm
