from langchain_core.messages import BaseMessage
from langchain_openai import ChatOpenAI

from .base import BaseLLM


class OpenAIModel(BaseLLM):
    """
    OpenAI-based LLM implementation.
    Uses OpenAI Chat Completion models via LangChain.
    """

    def __init__(self, model_name: str = "gpt-4-turbo", **kwargs):
        """
        Initialize the OpenAI chat model.

        Parameters
        ----------
        model_name : str, default "gpt-4-turbo"
            The OpenAI model identifier (e.g., 'gpt-4o', 'gpt-3.5-turbo').
        **kwargs : dict
            Additional parameters passed to the ChatOpenAI constructor, 
            such as 'temperature', 'max_tokens', or 'api_key'.
        """
        self._llm = ChatOpenAI(model=model_name, **kwargs)

    def generate(self, messages: list[BaseMessage]) -> str:
        """
        Generate a text response from a list of structured messages.

        Parameters
        ----------
        messages : list[BaseMessage]
            A sequence of messages representing the conversation history 
            (System, Human, AI).

        Returns
        -------
        str
            The text content generated by the OpenAI model.
        """
        response = self._llm.invoke(messages)
        return response.content

    @property
    def runnable(self):
        """
        Expose the underlying LangChain runnable.

        This property is essential for using the model within LCEL 
        (LangChain Expression Language) for chaining and composition.

        Returns
        -------
        ChatOpenAI
            The internal ChatOpenAI instance.
        """
        return self._llm
